[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
StringManipulation = "892a3eda-7b42-436c-8928-eab12a02cf0e"
TerminalPager = "0c614874-6106-40ed-a7c2-2f1cd0bff883"

[compat]
BenchmarkTools = "1"
PrettyTables = "3"
TerminalPager = "0.6"
julia = "1.10"
