## Description #############################################################################
#
# Helpers.
#
############################################################################################

export @help, @stdout_to_pager, @out2pr

const _HELP_PAGER = Ref{Any}((args...; kwargs...) -> pager(args...; kwargs...))
const _HELP_GETTER = Ref{Any}()

"""
    @help(f)

Open the documentation of the function, macro or other object `f` in pager.

# Arguments

- `f`: Expression that identifies the documented binding.

# Examples

```julia-repl
julia> @help write
```
"""
macro help(f)
    # Get the string representation of `f`.
    # When calling @help for a macro, the resulting `Expr` contains a `LineNumberNode`
    # jumbling the resulting string, so use the `Symbol` instead.
    f_str = string(Meta.isexpr(f, :macrocall) ? f.args[1] : f)

    ex_out = quote
        $TerminalPager._show_help($f_str)
    end

    return esc(ex_out)
end

"""
    @stdout_to_pager(ex_in, pager_args...)

Capture the `stdout` generated by `ex_in` and show inside a pager.

`pager_args` are the keyword arguments of the `pager` function.

# Arguments

- `ex_in`: Expression whose standard output is captured.
- `pager_args...`: Pager keyword assignments forwarded to [`pager`](@ref).

See also [`pager`](@ref).

!!! note
    The command **must** write to `stdout` explicitly. For example, `@stdout_to_pager 1`
    shows a blank screen since `1` does not write to `stdout`, but returns `1`.
    `@stdout_to_pager show(1)`, on the other hand, shows the number `1` inside the pager.

!!! note
    This macro can also be called using the shorter name `@out2pr` if no pager_args are
    needed.
"""
macro stdout_to_pager(ex_in, args...)
    all(x -> Meta.isexpr(x, :(=)), args) ||
        "All additional arguments to @stdout_to_pager must be keyword arguments." |>
        MethodError |> throw
    # Convert args from macro expressions to keyword arguments.
    kwargs = map(x -> Expr(:kw, x.args[1], x.args[2]), args)

    ex_out = quote
        hascolor     = get(stdout, :color, true)
        bypass_pager = get(stdout, :bypass_pager, false)
        old_stdout   = stdout
        buf          = IOBuffer()

        io = IOContext(
            buf,
            :bypass_pager => bypass_pager,
            :color        => hascolor,
            :limit        => false,
        )

        try
            Base.eval(:(stdout = $io))
            $(esc(ex_in))
            Base.eval(:(stdout = $old_stdout))
            pager(String(take!(buf)); $(kwargs...))
            close(io)
        finally
            Base.eval(:(stdout = $old_stdout))
        end

    end

    return ex_out
end

"""
    @out2pr(ex)

Capture the standard output generated by `ex` and show it in a pager.

# Arguments

- `ex`: Expression whose standard output is captured.
"""
macro out2pr(ex)
    return :(@stdout_to_pager $(esc(ex)))
end

############################################################################################
#                                    Private Functions                                     #
############################################################################################

"""
    _get_help(f::AbstractString, mod::Module = Base.active_module()) -> String

Render help for `f` in `mod`, falling back to `Main` when the binding is not found.

# Arguments

- `f::AbstractString`: Help query to render.
- `mod::Module`: Module in which to evaluate the help query first.
"""
function _get_help(f::AbstractString, mod::Module = Base.active_module())
    # Create a buffer that will replace `stdout`.
    buf = IOBuffer()
    io = IOContext(
        IOContext(buf, stdout),
        :displaysize => displaysize(stdout),
        :limit => false,
    )

    # Evaluate the AST, which returns a Markdown object.
    response = if ccall(:jl_generating_output, Cint, ()) == 1
        # If we are precompiling, just return a sample markdown. We still invoke
        # `REPL.helpmode` so that it gets precompiled via the precompile workload, but
        # skip `Core.eval` because evaluating the resulting AST into a module during
        # precompilation is not desirable. The `mod` argument does not affect which method
        # instance is compiled (`Module` is a concrete type), so we simply let `helpmode`
        # use its default.
        Base.invokelatest(TerminalPager.REPL.helpmode, io, f)

        md"""
        # Header

        This is a paragraph.

        ```julia
        a = 1 + 2
        ```

        ---
        """
    else
        # Try the REPL's active module first. If the binding cannot be resolved there,
        # fall back to `Main`, matching what the plain REPL would do. `REPL.helpmode`
        # behaves differently for the two "missing binding" cases we care about:
        #
        #   - Unqualified bindings missing in `mod` (e.g. `foo` when `foo` only exists in
        #     `Main`): it does **not** throw, but returns a "No documentation found"
        #     Markdown. We detect this and retry with `Main`.
        #   - Qualified bindings referencing a non-existing module (e.g. `Foo.bar` when
        #     `Foo` is undefined): it throws `UndefVarError`, which we catch and retry
        #     with `Main`.
        #
        # In both cases, if `Main` also cannot resolve the binding, we return a Markdown
        # object mimicking the REPL's "no documentation found" output instead of
        # propagating any error.
        try
            response = _eval_helpmode(io, f, mod)
            if mod !== Main && _is_not_found_response(response)
                try
                    response = _eval_helpmode(io, f, Main)
                catch err
                    err isa UndefVarError || rethrow()
                end
            end
            response
        catch err
            err isa UndefVarError || rethrow()
            try
                mod === Main ? rethrow() : _eval_helpmode(io, f, Main)
            catch err2
                err2 isa UndefVarError || rethrow()
                Markdown.parse(
                    "No documentation found.\n\nBinding `$(lstrip(f, '?'))` does not exist."
                )
            end
        end
    end

    # Render the output.
    show(io, MIME("text/plain"), response)
    write(io, '\n')

    str = String(take!(buf))

    close(io)

    return str
end

"""
    _show_help(f::AbstractString, mod::Module = Base.active_module()) -> Nothing

Show help for `f` in a pager, reporting errors in the same way as the public `@help` macro.

# Arguments

- `f::AbstractString`: Help query to display.
- `mod::Module`: Module in which to evaluate the help query first.
"""
function _show_help(f::AbstractString, mod::Module = Base.active_module())
    try
        help_text = _HELP_GETTER[](f, mod)
        _HELP_PAGER[](help_text; use_alternate_screen_buffer = true)
    catch err
        Base.display_error(stderr, err, Base.catch_backtrace())
    end

    return nothing
end

# Install the default help getter after defining it so extensions can replace the hook.
_HELP_GETTER[] = _get_help

"""
    _eval_helpmode(io::IO, f::AbstractString, mod::Module) -> Any

Run `REPL.helpmode` for `f` and evaluate its result in `mod`.

# Arguments

- `io::IO`: Output context passed to `REPL.helpmode`.
- `f::AbstractString`: Help query to evaluate.
- `mod::Module`: Module in which to evaluate the generated expression.
"""
function _eval_helpmode(io::IO, f::AbstractString, mod::Module)
    ast = Base.invokelatest(TerminalPager.REPL.helpmode, io, f, mod)
    return Core.eval(mod, ast)
end

"""
    _is_not_found_response(response::Any) -> Bool

Return whether `response` is the missing-documentation result produced by `REPL.helpmode`.

# Arguments

- `response::Any`: Help-mode response to inspect.
"""
function _is_not_found_response(response)
    response isa Markdown.MD && !isempty(response.content) || return false
    first = response.content[1]
    first isa Markdown.Paragraph || return false
    return first.content == ["No documentation found."]
end
